name: Build Project

on:
  push:
    branches: 
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: |
        mvn -B package --file pom.xml
    - name: Checkstyle
      run: |
        mvn -B test checkstyle:checkstyle
    - name: Archive Test Results
      if: always()
      run: |
        echo "# Checkstyle :rocket:" >> $GITHUB_STEP_SUMMARY
        cat ./target/surefire-reports/*.txt >> $GITHUB_STEP_SUMMARY